// File generated by FlutterFire CLI / AI Refactor.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstcV14pPZRs-npkj3jpbqx8_bKlmvQ9g',
    appId: '1:221306600744:web:0bc6438576d5e95f3e641d',
    messagingSenderId: '221306600744',
    projectId: 'meetingmind-ai-159c9',
    authDomain: 'meetingmind-ai-159c9.firebaseapp.com',
    storageBucket: 'meetingmind-ai-159c9.firebasestorage.app',
    measurementId: 'G-GWP4EKYBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-7rpP26nCuJ_hlYiYwvwZkEsavaYBuY',
    appId: '1:221306600744:android:0ba2e0cc15dad9f33e641d',
    messagingSenderId: '221306600744',
    projectId: 'meetingmind-ai-159c9',
    storageBucket: 'meetingmind-ai-159c9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForCompilationOnly',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'meetingmind-ai',
    storageBucket: 'meetingmind-ai.appspot.com',
    iosBundleId: 'com.meetingmind.ai.meetingmind_ai',
  );
}
